name: jd_jcookie

on:
    workflow_dispatch:
    schedule:
        - cron: "30 3,14 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_jcookie

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 京奇世界"
              run: python3 jd_jcookie.py
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ secrets.JD_DEBUG }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  SYNCURL: https://raw.githubusercontent.com/wangzyh/Demo/master/Scripts/JD_tools/jingqiWorld.py
